import { Varela_Round } from "next/font/google";
import Link from "next/link";

const varela = Varela_Round({
  weight: "400",
  subsets: ["latin"],
});

export default function PolicyPage() {
  return (
    <main className={`min-h-screen px-4 py-8 md:px-8 ${varela.className}`}>
      <div className="max-w-3xl mx-auto bg-white/90 backdrop-blur-lg rounded-3xl border border-gray-200 shadow-xl p-8">
        <h1 className="text-3xl font-bold text-center mb-6 text-purple-700">Privacy & Policy</h1>

        <section className="space-y-4 mb-8">
          <h2 className="text-xl font-semibold">What We Do</h2>
          <p className="text-gray-700 leading-7">
            MCQ-AI is a lightweight quiz generation tool that converts text into multiple-choice questions. We do not sell, share, or otherwise monetize your input data.
          </p>
          <p className="text-gray-700 leading-7">
            When you submit text, it is forwarded to the AI service to generate questions and answers. The submitted content is not retained in the app beyond processing.
          </p>
        </section>

        <section className="space-y-4 mb-8">
          <h2 className="text-xl font-semibold">Data and Privacy</h2>
          <p className="text-gray-700 leading-7">
            We do not collect personal information for the app to function. The site may use cookies or browser storage only to support basic user interactions and session state.
          </p>
          <p className="text-gray-700 leading-7">
            Please avoid submitting sensitive personal information, health data, passwords, or confidential material. The AI response may be generated by a third-party model and is not guaranteed to keep private content secure.
          </p>
        </section>

        <section className="space-y-4 mb-8">
          <h2 className="text-xl font-semibold">Third-Party Services</h2>
          <p className="text-gray-700 leading-7">
            MCQ-AI relies on an AI provider to generate quiz content. Any text you submit may be processed by that service, and its own privacy policies may apply.
          </p>
          <p className="text-gray-700 leading-7">
            The app does not directly manage or store API keys in client code. If you are using the service through this website, the provider handles the generation request.
          </p>
        </section>

        <section className="space-y-4 mb-8">
          <h2 className="text-xl font-semibold">Disclaimer</h2>
          <p className="text-gray-700 leading-7">
            Generated questions are provided as-is for study use only. The accuracy, completeness, and suitability of the output are not guaranteed. Always verify important information before relying on it.
          </p>
          <p className="text-gray-700 leading-7">
            This site is intended for educational support and does not replace professional advice or official exam preparation materials.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">Contact</h2>
          <p className="text-gray-700 leading-7">
            If you have questions about this policy or want to share feedback, please reach out through the contact options on the About page.
          </p>
        </section>

        <div className="mt-8 text-center">
          <Link
            href="/about"
            className="inline-block px-6 py-3 text-white bg-purple-600 rounded-full hover:bg-purple-700 transition"
          >
            Learn more about the site
          </Link>
        </div>
      </div>
    </main>
  );
}
